export const MEASUREMENT_UNITS = [
  { value: "g", label: "Grams (g)" },
  { value: "kg", label: "Kilograms (kg)" },
  { value: "ml", label: "Milliliters (ml)" },
  { value: "l", label: "Liters (l)" },
  { value: "tsp", label: "Teaspoon (tsp)" },
  { value: "tbsp", label: "Tablespoon (tbsp)" },
  { value: "cup", label: "Cup" },
  { value: "oz", label: "Ounce (oz)" },
  { value: "lb", label: "Pound (lb)" },
  { value: "piece", label: "Piece" },
  { value: "can", label: "Can" },
  { value: "clove", label: "Clove" },
  { value: "pinch", label: "Pinch" },
  { value: "stick", label: "Stick" },
  { value: "jar", label: "Jar" },
  { value: "bottle", label: "Bottle" },
  { value: "pack", label: "Pack" },
  { value: "box", label: "Box" },
  { value: "bunch", label: "Bunch" },
  { value: "head", label: "Head" },
  { value: "bag", label: "Bag" },
  { value: "container", label: "Container" },
] as const;

export const UNIT_MAP: Record<string, string> = {
  tablespoon: "tbsp",
  tablespoons: "tbsp",
  "table spoon": "tbsp",
  "table spoons": "tbsp",
  tb: "tbsp",
  "tb.": "tbsp",
  tbsp: "tbsp",
  teaspoon: "tsp",
  teaspoons: "tsp",
  "tea spoon": "tsp",
  "tea spoons": "tsp",
  tsp: "tsp",
  ounce: "oz",
  ounces: "oz",
  "oz.": "oz",
  oz: "oz",
  pound: "lb",
  pounds: "lb",
  "lb.": "lb",
  "lbs.": "lb",
  lbs: "lb",
  lb: "lb",
  gram: "g",
  grams: "g",
  kilogram: "kg",
  kilograms: "kg",
  milliliter: "ml",
  milliliters: "ml",
  liter: "l",
  liters: "l",
  cloves: "clove",
  cups: "cup",
  cup: "cup",
  "c.": "cup",
  c: "cup",
  can: "can",
  cans: "can",
  jar: "jar",
  jars: "jar",
  bottle: "bottle",
  bottles: "bottle",
  pack: "pack",
  packs: "pack",
  package: "pack",
  packages: "pack",
  box: "box",
  boxes: "box",
  bunch: "bunch",
  bunches: "bunch",
  head: "head",
  heads: "head",
  stick: "stick",
  sticks: "stick",
  pinch: "pinch",
  pinches: "pinch",
  bag: "bag",
  bags: "bag",
  container: "container",
  containers: "container",
};

export const STANDARD_UNITS = [
  "g",
  "kg",
  "ml",
  "l",
  "oz",
  "lb",
  "cup",
  "tbsp",
  "tsp",
  "piece",
  "can",
  "clove",
  "jar",
  "bottle",
  "pack",
  "box",
  "bunch",
  "head",
  "stick",
  "pinch",
  "bag",
  "container",
];
