export const CATEGORY_OPTIONS = ["Breakfast", "Lunch", "Dinner", "Snack", "Dessert", "Drink"];

export const CUISINE_OPTIONS = [
  "Italian",
  "French",
  "Spanish",
  "Greek",
  "German",
  "British",
  "Portuguese",
  "Scandinavian",
  "Chinese",
  "Japanese",
  "Korean",
  "Thai",
  "Vietnamese",
  "Indian",
  "Pakistani",
  "Malaysian",
  "Indonesian",
  "Filipino",
  "Middle Eastern",
  "Turkish",
  "Lebanese",
  "Moroccan",
  "Ethiopian",
  "American",
  "Tex-Mex",
  "Southern",
  "Cajun",
  "Mexican",
  "Brazilian",
  "Peruvian",
  "Argentinian",
  "Caribbean",
  "West African",
  "South African",
  "Mediterranean",
  "Australian",
  "Fusion",
];

export const SORT_OPTIONS = [
  { value: "default", label: "Default" },
  { value: "name", label: "Name" },
  { value: "calories", label: "Calories" },
  { value: "protein", label: "Protein" },
  { value: "carbs", label: "Carbs" },
  { value: "fat", label: "Fat" },
  { value: "time", label: "Time" },
];
